---
title: '離散選択モデル: 演習編'
subtitle: '応用社会科学RAブートキャンプ'
author: '講師: 遠山祐太 (早稲田大学)'
date: '最終更新: `r format(Sys.time(), format = "%Y-%m-%d %X")`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      countIncrementalSlides: no
      highlightLines: yes
      highlightStyle: github
      ratio: '16:9'
fig_width: 6
fig_height: 4
knit: pagedown::chrome_print

---
class: title-slide-section, center, middle
name: logistics
# 演習課題


---
## はじめに

- 演習として４つ課題を用意しています。順番に取り組んでください。


- なお、課題１・２については講師の方でもある程度確認していますが、課題３・４については行っていません。よって、思わぬエラーなどがあるかもしれません（特に課題４）。

---
## 課題１：新データでの再現エクササイズ


- 皆さんに回答してもらったきのこ・たけのこサーベイの結果が`data/KinokoTakenokoSurvey_RABootcamp2024.csv` にあります。

- このデータを用いて、講義パートで行った分析(`mlogit`での推定)を再現してください。
  - 消費者属性なしの多項ロジットモデルに取り組んでください。


- コメント：データは最低限のクリーニングをしたもの。    
  - 変数名は講義パートのデータ(`data/KinokoTakenokoSurvey_IOSpring2024.csv`)と同じ
  - 変数の中身は、講義パートと若干異なっている部分があるので要注意。
  - データ共有についての不同意者の回答を落としている。

---
## 課題２：支払い意思額の計算・価格弾力性の計算


- 以下では消費者属性なしのモデル＋ブートキャンプデータで考えます。


- 推定結果に基づき、きのこの山・たけのこの里への支払い意思額を求めてください。


- きのこの山とたけのこの里の価格が両方200円だったときの、きのこの山の自己価格弾力性を計算してください。

---
## 課題３：ランダム係数ロジット

- 新データを利用して、ランダム係数ロジットモデルの推定をしてください。なお、余裕があれば、係数の分布のプロット、需要関数のプロットなども取り組んでください。


---
## 【チャレンジ】課題４：消費者属性を利用した多項ロジット

- 新データを利用して、消費者属性を利用した多項ロジットモデルを推定してください。


- なお、新データでは、講義コード通りの定式化では推定がうまくいきません。なぜ上手く行かないか？、またどのような定式化にすればよいか、を考えてください。


- 【ヒント】消費者属性の分布について見てみましょう。
